### ISSUE TITLE
ventura_upgrade_supported.py and sonoma_upgrade_supported.py are returning False on vm's

### ISSUE THREAD

**Issue by SoxIn4** [munki/munki-facts#33]
I'm not in a position to make a pull request right now, but I found that the monterey version has this at the top of its sysctl function, and it's missing in the newer versions:
https://github.com/munki/munki-facts/blob/0ed30ec013940644fbee1c35e6e5e314d8116c05/facts/monterey_upgrade_supported.py#L63-L64

Adding that to the new versions seems to work in my local testing. (Can't test for real until Wed.)

**Comment by gregneagle** [comment]
Untested, but https://github.com/munki/munki-facts/commit/97842665f7612a43a0109a69bb963f590f60f2d4 should address.

**Comment by gregneagle** [comment]
Closing due to lack of updates.
