### ISSUE TITLE
facts that trace cause munki-facts to trace

### ISSUE THREAD

**Issue by erikng** [munki/munki-facts#9]
if munki-facts has a script that has a python trace error, it will cause munki-facts to also fail.

Munki-facts should handle this and move on to the next fact, without losing the other conditions.

**Comment by gregneagle** [comment]
I would accept a PR that addresses this. Or if you aren't likely to provide one, could you at least provide a fact that fails?

**Comment by erikng** [comment]
I can provide one later today. I was issuing an issue just so I wouldn't forget.

Thanks,
Erik Gomez
________________________________

**Comment by erikng** [comment]
https://gist.github.com/erikng/3246bed1ad1d87345ec38dddd2254fb8

This should trace at the loginwindow, due to a TypeError (ultimately caused by user being `None`). if you name it something like `a_fact.py` it will be one of the first facts ran.

**Comment by gregneagle** [comment]
https://github.com/munki/munki-facts/commit/365c45bb7fb09a201c42a672835a624ad1c99a12 should address this.
